### ISSUE TITLE
undefined reference to `i2c_smbus_write_byte_data

### ISSUE THREAD

**Issue by feiticeir0** [polarpiberry/MPU6050-C-CPP-Library-for-Raspberry-Pi#4] opened 2020-06-30 16:01 UTC
Hi ! 
I'm trying to compile the example in your library, but I get the following error:

` make example
g++ Example.cpp -o Example -lMPU6050 -pthread
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/8/../../../libMPU6050.so: undefined reference to `i2c_smbus_write_byte_data(int, unsigned char, unsigned char)'
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/8/../../../libMPU6050.so: undefined reference to `i2c_smbus_read_byte_data(int, unsigned char)'
collect2: error: ld returned 1 exit status
make: *** [Makefile:15: example] Error 1`

Compiling and installing the library went well, without any issues... 

I've installed libi2c-dev 

How can I solve this ? 

Thank you

**Comment by azaslavskis** [comment] 2020-08-23 18:01
Same problem

**Comment by prateekj117** [comment] 2020-10-14 04:54
@feiticeir0 @alex5250 Facing the same issue. Were you able to solve this?

**Comment by azaslavskis** [comment] 2020-10-14 06:48
Not yet

**Comment by prateekj117** [comment] 2020-10-14 06:49
@alex5250 https://stackoverflow.com/a/51298384/9169348 Try this.

**Comment by azaslavskis** [comment] 2020-10-14 07:20
Already tried. Not make any sense

**Comment by alex-mous** [comment] 2020-10-29 02:41
@feiticeir0 @alex5250 @prateekj117 I'll try to see if I can get a fix to this and provide an update

**Comment by austinbeauch** [comment] 2020-10-29 07:43
+1. Hopefully it'll be a nice an easy fix

**Comment by feiticeir0** [comment] 2020-10-29 08:48
Thank you ! Hope it will be easy !

**Comment by alex-mous** [comment] 2020-10-29 18:21
@feiticeir0 @austinbeauch @alex5250 @prateekj117 I think the issue is fixed! I believe there was a linking error from an the update to Raspbian Buster. I changed the Makefile and updated the header file, so it should now work (tested on a Raspberry Pi 3B with Raspbian Buster). I'm going to close the issue. If it still persists, please re-open or create a new one.

**Closed as completed by alex-mous** 2020-10-29 18:21 UTC

**Comment by azaslavskis** [comment] 2020-10-29 19:11
All right ! 
The bug is gone.
Tested on Ubuntu Server 18.0.4.5 LTS and Ubuntu  18.0.4.5 LTS  and Raspberry Pi OS (32-bit) Lite dated  :  2020-08-20.
Thanks so much for that .
